name: Stars

on:
  watch:
    types: [started]
  workflow_call:
    secrets:
      ntfy_url:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Print Info
        run: |
          REPO="$(echo '${{ github.repository }}' | cut -d'/' -f2)"
          echo "Repository: $REPO"
          echo "Event: ${{ github.event_name }}"
          echo "User: ${{ github.actor }}"
          echo "Done!"
      - name: Ntfy
        run: |
          REPO="$(echo '${{ github.repository }}' | cut -d'/' -f2)"
          curl -H "Title: ${{ github.repository }}" -d "${{ github.actor }} starred your repository." ${{ secrets.ntfy_url }}
      - name: Telegram
        id: send_message
        uses: akeylimepie/telegram-action@main
        with:
          token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
          parse_mode: html
          disable_notification: true
          text: |
            ${{ github.actor }} starred your repository <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
      - run: |
          echo "Message ID: ${{ steps.send_message.outputs.message_id }}"# custom message
